/*

Copyright (C) 2015 by Marijn Haverbeke <marijnh@gmail.com> and others

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
(function(m){"object"==typeof exports&&"object"==typeof module?m(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],m):m(CodeMirror)})(function(m){m.defineMIME("text/x-erlang","erlang");m.defineMode("erlang",function(y){function z(a,b){if(b.in_string)return b.in_string=!q(a,'"',"\\"),c(b,a,"string");if(b.in_atom)return b.in_atom=!q(a,"'","\\"),c(b,a,"atom");if(a.eatSpace())return c(b,a,"whitespace");if(!p(b)&&a.match(/-\s*[a-z\u00df-\u00f6\u00f8-\u00ff][\w\u00d8-\u00de\u00c0-\u00d6\u00df-\u00f6\u00f8-\u00ff]*/))return f(a.current(),
A)?c(b,a,"type"):c(b,a,"attribute");var d=a.next();if("%"==d)return a.skipToEnd(),c(b,a,"comment");if(":"==d)return c(b,a,"colon");if("?"==d)return a.eatSpace(),a.eatWhile(r),c(b,a,"macro");if("#"==d)return a.eatSpace(),a.eatWhile(r),c(b,a,"record");if("$"==d)return"\\"!=a.next()||a.match(B)?c(b,a,"number"):c(b,a,"error");if("."==d)return c(b,a,"dot");if("'"==d){if(!(b.in_atom=!q(a,"'","\\"))){if(a.match(/\s*\/\s*[0-9]/,!1))return a.match(/\s*\/\s*[0-9]/,!0),c(b,a,"fun");if(a.match(/\s*\(/,!1)||a.match(/\s*:/,
!1))return c(b,a,"function")}return c(b,a,"atom")}if('"'==d)return b.in_string=!q(a,'"',"\\"),c(b,a,"string");if(/[A-Z_\u00d8-\u00de\u00c0-\u00d6]/.test(d))return a.eatWhile(r),c(b,a,"variable");if(/[a-z_\u00df-\u00f6\u00f8-\u00ff]/.test(d)){a.eatWhile(r);if(a.match(/\s*\/\s*[0-9]/,!1))return a.match(/\s*\/\s*[0-9]/,!0),c(b,a,"fun");d=a.current();if(f(d,C))return c(b,a,"keyword");if(f(d,D))return c(b,a,"operator");if(a.match(/\s*\(/,!1))return!f(d,E)||":"==p(b).token&&"erlang"!=p(b,2).token?f(d,F)?
c(b,a,"guard"):c(b,a,"function"):c(b,a,"builtin");var e=a.match(/([\n\s]+|%[^\n]*\n)*(.)/,!1);return":"==(e?e.pop():"")?"erlang"==d?c(b,a,"builtin"):c(b,a,"function"):f(d,["true","false"])?c(b,a,"boolean"):c(b,a,"atom")}var e=/[0-9]/,g=/[0-9a-zA-Z]/;return e.test(d)?(a.eatWhile(e),a.eat("#")?a.eatWhile(g)||a.backUp(1):a.eat(".")&&(a.eatWhile(e)?a.eat(/[eE]/)&&(a.eat(/[-+]/)?a.eatWhile(e)||a.backUp(2):a.eatWhile(e)||a.backUp(1)):a.backUp(1)),c(b,a,"number")):v(a,G,t)?c(b,a,"open_paren"):v(a,H,w)?c(b,
a,"close_paren"):x(a,I,J)?c(b,a,"separator"):x(a,K,L)?c(b,a,"operator"):c(b,a,null)}function v(a,b,d){if(1==a.current().length&&b.test(a.current())){for(a.backUp(1);b.test(a.peek());)if(a.next(),f(a.current(),d))return!0;a.backUp(a.current().length-1)}return!1}function x(a,b,d){if(1==a.current().length&&b.test(a.current())){for(;b.test(a.peek());)a.next();for(;0<a.current().length;){if(f(a.current(),d))return!0;a.backUp(1)}a.next()}return!1}function q(a,b,d){for(;!a.eol();){var e=a.next();if(e==b)return!0;
e==d&&a.next()}return!1}function f(a,b){return-1<b.indexOf(a)}function c(a,b,d){var e;e=b.current();var g=b.column();b=b.indentation();e={token:e,column:g,indent:b,type:d};"comment"!=e.type&&"whitespace"!=e.type&&(g=a.tokenStack,b=g.length-1,0<b&&"record"===g[b].type&&"dot"===e.type?g.pop():(0<b&&"group"===g[b].type&&g.pop(),g.push(e)),a.tokenStack=g,a.tokenStack=M(a.tokenStack));switch(d){case "atom":return"atom";case "attribute":return"attribute";case "boolean":return"atom";case "builtin":return"builtin";
case "close_paren":return null;case "colon":return null;case "comment":return"comment";case "dot":return null;case "error":return"error";case "fun":return"meta";case "function":return"tag";case "guard":return"property";case "keyword":return"keyword";case "macro":return"variable-2";case "number":return"number";case "open_paren":return null;case "operator":return"operator";case "record":return"bracket";case "separator":return null;case "string":return"string";case "type":return"def";case "variable":return"variable";
default:return null}}function N(a){return{token:a,column:0,indent:0,type:a}}function p(a,b){var d=a.tokenStack.length,e=b?b:1;return d<e?!1:a.tokenStack[d-e]}function M(a){var b=a.length-1;if("dot"===a[b].type)return[];if("fun"===a[b].type&&"fun"===a[b-1].token)return a.slice(0,b-1);switch(a[a.length-1].token){case "}":return l(a,{g:["{"]});case "]":return l(a,{i:["["]});case ")":return l(a,{i:["("]});case ">>":return l(a,{i:["<<"]});case "end":return l(a,{i:"begin case fun if receive try".split(" ")});
case ",":return l(a,{e:"begin try when -> , ( [ { <<".split(" ")});case "->":return l(a,{r:["when"],m:["try","if","case","receive"]});case ";":return l(a,{E:"case fun if receive try when".split(" ")});case "catch":return l(a,{e:["try"]});case "of":return l(a,{e:["case"]});case "after":return l(a,{e:["receive","try"]});default:return a}}function l(a,b){for(var d in b)for(var e=a.length-1,g=b[d],c=e-1;-1<c;c--)if(f(a[c].token,g)){var h=a.slice(0,c);switch(d){case "m":return h.concat(a[c]).concat(a[e]);
case "r":return h.concat(a[e]);case "i":return h;case "g":return h.concat(N("group"));case "E":return h.concat(a[c]);case "e":return h.concat(a[c])}}return"E"==d?[]:a}function O(a,b){var d,e=y.indentUnit,c;c=b.match(/,|[a-z]+|\}|\]|\)|>>|\|+|\(/);c=n(c)&&0===c.index?c[0]:"";var k=p(a,1),h=p(a,2);if(a.in_string||a.in_atom)return m.Pass;if(h){if("when"==k.token)return k.column+e;if("when"===c&&"function"===h.type)return h.indent+e;if("("===c&&"fun"===k.token)return k.column+3;if("catch"===c&&(d=u(a,
["try"])))return d.column;if(f(c,["end","after","of"]))return(d=u(a,"begin case fun if receive try".split(" ")))?d.column:m.Pass;if(f(c,w))return(d=u(a,t))?d.column:m.Pass;if(f(k.token,[",","|","||"])||f(c,[",","|","||"]))return d=a.tokenStack.slice(0,-1),c=s(d,"type",["open_paren"]),(d=n(d[c])?d[c]:!1)?d.column+d.token.length:e;if("->"==k.token)return f(h.token,["receive","case","if","try"])?h.column+e+e:h.column+e;if(f(k.token,t))return k.column+k.token.length;d=a.tokenStack;c=s(d,"type",["open_paren",
"separator","keyword"]);k=s(d,"type",["operator"]);d=n(c)&&n(k)&&c<k?d[c+1]:n(c)?d[c]:!1;return n(d)?d.column+e:0}return 0}function u(a,b){var c=a.tokenStack,e=s(c,"token",b);return n(c[e])?c[e]:!1}function s(a,b,c){for(var e=a.length-1;-1<e;e--)if(f(a[e][b],c))return e;return!1}function n(a){return!1!==a&&null!=a}var A=["-type","-spec","-export_type","-opaque"],C="after begin catch case cond end fun if let of query receive try when".split(" "),I=/[\->,;]/,J=["->",";",","],D="and andalso band bnot bor bsl bsr bxor div not or orelse rem xor".split(" "),
K=/[\+\-\*\/<>=\|:!]/,L="= + - * / > >= < =< =:= == =/= /= || <- !".split(" "),G=/[<\(\[\{]/,t=["<<","(","[","{"],H=/[>\)\]\}]/,w=["}","]",")",">>"],F="is_atom is_binary is_bitstring is_boolean is_float is_function is_integer is_list is_number is_pid is_port is_record is_reference is_tuple atom binary bitstring boolean function integer list number pid port record reference tuple".split(" "),E="abs adler32 adler32_combine alive apply atom_to_binary atom_to_list binary_to_atom binary_to_existing_atom binary_to_list binary_to_term bit_size bitstring_to_list byte_size check_process_code contact_binary crc32 crc32_combine date decode_packet delete_module disconnect_node element erase exit float float_to_list garbage_collect get get_keys group_leader halt hd integer_to_list internal_bif iolist_size iolist_to_binary is_alive is_atom is_binary is_bitstring is_boolean is_float is_function is_integer is_list is_number is_pid is_port is_process_alive is_record is_reference is_tuple length link list_to_atom list_to_binary list_to_bitstring list_to_existing_atom list_to_float list_to_integer list_to_pid list_to_tuple load_module make_ref module_loaded monitor_node node node_link node_unlink nodes notalive now open_port pid_to_list port_close port_command port_connect port_control pre_loaded process_flag process_info processes purge_module put register registered round self setelement size spawn spawn_link spawn_monitor spawn_opt split_binary statistics term_to_binary time throw tl trunc tuple_size tuple_to_list unlink unregister whereis".split(" "),
r=/[\w@\u00d8-\u00de\u00c0-\u00d6\u00df-\u00f6\u00f8-\u00ff]/,B=/[0-7]{1,3}|[bdefnrstv\\"']|\^[a-zA-Z]|x[0-9a-zA-Z]{2}|x{[0-9a-zA-Z]+}/;return{startState:function(){return{tokenStack:[],in_string:!1,in_atom:!1}},token:function(a,b){return z(a,b)},indent:function(a,b){return O(a,b)},lineComment:"%"}})});
