/*

Copyright (C) 2015 by Marijn Haverbeke <marijnh@gmail.com> and others

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
(function(k){"object"==typeof exports&&"object"==typeof module?k(require("../../lib/codemirror")):"function"==typeof define&&define.amd?define(["../../lib/codemirror"],k):k(CodeMirror)})(function(k){function c(a){var b={};a=a.split(" ");for(var c=0;c<a.length;++c)b[a[c]]=!0;return b}function q(a,b){return"function"===typeof a?a(b):a.propertyIsEnumerable(b)}function l(a,b){if(!b.startOfLine)return!1;for(;;)if(a.skipTo("\\")){if(a.next(),a.eol()){b.tokenize=l;break}}else{a.skipToEnd();b.tokenize=null;
break}return"meta"}function s(a,b){return"variable-3"==b.prevToken?"variable-3":!1}function f(a){a.eatWhile(/[\w\.']/);return"number"}function m(a,b){a.backUp(1);if(a.match(/(R|u8R|uR|UR|LR)/)){var c=a.match(/"([^\s\\()]{0,16})\(/);if(!c)return!1;b.cpp11RawStringDelim=c[1];b.tokenize=u;return u(a,b)}if(a.match(/(u8|u|U|L)/))return a.match(/["']/,!1)?"string":!1;a.next();return!1}function v(a,b){for(var c;null!=(c=a.next());)if('"'==c&&!a.eat('"')){b.tokenize=null;break}return"string"}function u(a,
b){var c=b.cpp11RawStringDelim.replace(/[^\w\s]/g,"\\$&");a.match(new RegExp(".*?\\)"+c+'"'))?b.tokenize=null:a.skipToEnd();return"string"}function e(a,b){function c(a){if(a)for(var b in a)a.hasOwnProperty(b)&&e.push(b)}"string"==typeof a&&(a=[a]);var e=[];c(b.keywords);c(b.types);c(b.builtin);c(b.atoms);e.length&&(b.helperType=a[0],k.registerHelper("hintWords",a[0],e));for(var f=0;f<a.length;++f)k.defineMIME(a[f],b)}function x(a,b){for(var c=!1;!a.eol();){if(!c&&a.match('"""')){b.tokenize=null;break}c=
"\\"==a.next()&&!c}return"string"}function w(a){return function(b,c){for(var e=!1,f,k=!1;!b.eol();){if(!e&&b.match('"')&&("single"==a||b.match('""'))){k=!0;break}if(!e&&b.match("``")){n=w(a);k=!0;break}f=b.next();e="single"==a&&!e&&"\\"==f}k&&(c.tokenize=null);return"string"}}k.defineMode("clike",function(a,b){function c(a,b){var d=a.next();if(r[d]){var g=r[d](a,b);if(!1!==g)return g}if('"'==d||"'"==d)return b.tokenize=e(d),b.tokenize(a,b);if(D.test(d))return h=d,null;if(E.test(d))return a.eatWhile(/[\w\.]/),
"number";if("/"==d){if(a.eat("*"))return b.tokenize=f,f(a,b);if(a.eat("/"))return a.skipToEnd(),"comment"}if(z.test(d))return a.eatWhile(z),"operator";a.eatWhile(/[\w\$_\xa1-\uffff]/);if(A)for(;a.match(A);)a.eatWhile(/[\w\$_\xa1-\uffff]/);d=a.current();return q(v,d)?(q(B,d)&&(h="newstatement"),q(F,d)&&(y=!0),"keyword"):q(w,d)?"variable-3":q(x,d)?(q(B,d)&&(h="newstatement"),"builtin"):q(G,d)?"atom":"variable"}function e(a){return function(b,d){for(var c=!1,e,f=!1;null!=(e=b.next());){if(e==a&&!c){f=
!0;break}c=!c&&"\\"==e}if(f||!c&&!H)d.tokenize=null;return"string"}}function f(a,b){for(var c=!1,g;g=a.next();){if("/"==g&&c){b.tokenize=null;break}c="*"==g}return"comment"}function l(a,b,c,g,e){this.indented=a;this.column=b;this.type=c;this.align=g;this.prev=e}function p(a){return"statement"==a||"switchstatement"==a||"namespace"==a}function m(a,b,c){var e=a.indented;a.context&&p(a.context.type)&&!p(c)&&(e=a.context.indented);return a.context=new l(e,b,c,null,a.context)}function t(a){var b=a.context.type;
if(")"==b||"]"==b||"}"==b)a.indented=a.context.indented;return a.context=a.context.prev}var n=a.indentUnit,s=b.statementIndentUnit||n,u=b.dontAlignCalls,v=b.keywords||{},w=b.types||{},x=b.builtin||{},B=b.blockKeywords||{},F=b.defKeywords||{},G=b.atoms||{},r=b.hooks||{},H=b.multiLineStrings,I=!1!==b.indentStatements,C=!1!==b.indentSwitch,A=b.namespaceSeparator,D=b.isPunctuationChar||/[\[\]{}\(\),;\:\.]/,E=b.isNumberChar||/\d/,z=b.isOperatorChar||/[+\-*&%=<>!?|\/]/,J=b.endStatement||/^[;:,]$/,h,y;return{startState:function(a){return{tokenize:null,
context:new l((a||0)-n,0,"top",!1),indented:0,startOfLine:!0,prevToken:null}},token:function(a,e){var d=e.context;a.sol()&&(null==d.align&&(d.align=!1),e.indented=a.indentation(),e.startOfLine=!0);if(a.eatSpace())return null;h=y=null;var g=(e.tokenize||c)(a,e);if("comment"==g||"meta"==g)return g;null==d.align&&(d.align=!0);if(J.test(h))for(;p(e.context.type);)t(e);else if("{"==h)m(e,a.column(),"}");else if("["==h)m(e,a.column(),"]");else if("("==h)m(e,a.column(),")");else if("}"==h){for(;p(d.type);)d=
t(e);for("}"==d.type&&(d=t(e));p(d.type);)d=t(e)}else h==d.type?t(e):I&&(("}"==d.type||"top"==d.type)&&";"!=h||p(d.type)&&"newstatement"==h)&&(d="statement","newstatement"==h&&C&&"switch"==a.current()?d="switchstatement":"keyword"==g&&"namespace"==a.current()&&(d="namespace"),m(e,a.column(),d));if((d="variable"==g)&&!(d="def"==e.prevToken)){if(d=b.typeFirstDefinitions)d="variable"==e.prevToken||"variable-3"==e.prevToken?!0:/\S(?:[^- ]>|[*\]])\s*$|\*$/.test(a.string.slice(0,a.start))?!0:void 0;if(d)a:for(d=
e.context;;){if(!d||"top"==d.type){d=!0;break a}if("}"==d.type&&"namespace"!=d.prev.type){d=!1;break a}d=d.prev}d=d&&a.match(/^\s*\(/,!1)}d&&(g="def");r.token&&(d=r.token(a,e,g),void 0!==d&&(g=d));"def"==g&&!1===b.styleDefs&&(g="variable");e.startOfLine=!1;e.prevToken=y?"def":g||h;return g},indent:function(a,b){if(a.tokenize!=c&&null!=a.tokenize)return k.Pass;var d=a.context,e=b&&b.charAt(0);p(d.type)&&"}"==e&&(d=d.prev);if(r.indent){var f=r.indent(a,d,b);if("number"==typeof f)return f}var f=e==d.type,
h=d.prev&&"switchstatement"==d.prev.type;return p(d.type)?d.indented+("{"==e?0:s):!d.align||u&&")"==d.type?")"!=d.type||f?d.indented+(f?0:n)+(f||!h||/^(?:case|default)\b/.test(b)?0:n):d.indented+s:d.column+(f?0:1)},electricInput:C?/^\s*(?:case .*?:|default:|\{\}?|\})$/:/^\s*[{}]$/,blockCommentStart:"/*",blockCommentEnd:"*/",lineComment:"//",fold:"brace"}});e(["text/x-csrc","text/x-c","text/x-chdr"],{name:"clike",keywords:c("auto if break case register continue return default do sizeof static else struct switch extern typedef float union for goto while enum const volatile"),
types:c("int long char short double float unsigned signed void size_t ptrdiff_t bool _Complex _Bool float_t double_t intptr_t intmax_t int8_t int16_t int32_t int64_t uintptr_t uintmax_t uint8_t uint16_t uint32_t uint64_t"),blockKeywords:c("case do else for if switch while struct"),defKeywords:c("struct"),typeFirstDefinitions:!0,atoms:c("null true false"),hooks:{"#":l,"*":s},modeProps:{fold:["brace","include"]}});e(["text/x-c++src","text/x-c++hdr"],{name:"clike",keywords:c("auto if break case register continue return default do sizeof static else struct switch extern typedef float union for goto while enum const volatile asm dynamic_cast namespace reinterpret_cast try explicit new static_cast typeid catch operator template typename class friend private this using const_cast inline public throw virtual delete mutable protected alignas alignof constexpr decltype nullptr noexcept thread_local final static_assert override"),
types:c("int long char short double float unsigned signed void size_t ptrdiff_t bool wchar_t"),blockKeywords:c("catch class do else finally for if struct switch try while"),defKeywords:c("class namespace struct enum union"),typeFirstDefinitions:!0,atoms:c("true false null"),hooks:{"#":l,"*":s,u:m,U:m,L:m,R:m,0:f,1:f,2:f,3:f,4:f,5:f,6:f,7:f,8:f,9:f,token:function(a,b,c){if(b="variable"==c&&"("==a.peek()&&(";"==b.prevToken||null==b.prevToken||"}"==b.prevToken))a=a.current(),b=(a=/(\w+)::(\w+)$/.exec(a))&&
a[1]==a[2];if(b)return"def"}},namespaceSeparator:"::",modeProps:{fold:["brace","include"]}});e("text/x-java",{name:"clike",keywords:c("abstract assert break case catch class const continue default do else enum extends final finally float for goto if implements import instanceof interface native new package private protected public return static strictfp super switch synchronized this throw throws transient try volatile while"),types:c("byte short int long float double boolean char void Boolean Byte Character Double Float Integer Long Number Object Short String StringBuffer StringBuilder Void"),
blockKeywords:c("catch class do else finally for if switch try while"),defKeywords:c("class interface package enum"),typeFirstDefinitions:!0,atoms:c("true false null"),endStatement:/^[;:]$/,hooks:{"@":function(a){a.eatWhile(/[\w\$_]/);return"meta"}},modeProps:{fold:["brace","import"]}});e("text/x-csharp",{name:"clike",keywords:c("abstract as async await base break case catch checked class const continue default delegate do else enum event explicit extern finally fixed for foreach goto if implicit in interface internal is lock namespace new operator out override params private protected public readonly ref return sealed sizeof stackalloc static struct switch this throw try typeof unchecked unsafe using virtual void volatile while add alias ascending descending dynamic from get global group into join let orderby partial remove select set value var yield"),
types:c("Action Boolean Byte Char DateTime DateTimeOffset Decimal Double Func Guid Int16 Int32 Int64 Object SByte Single String Task TimeSpan UInt16 UInt32 UInt64 bool byte char decimal double short int long object sbyte float string ushort uint ulong"),blockKeywords:c("catch class do else finally for foreach if struct switch try while"),defKeywords:c("class interface namespace struct var"),typeFirstDefinitions:!0,atoms:c("true false null"),hooks:{"@":function(a,b){if(a.eat('"'))return b.tokenize=
v,v(a,b);a.eatWhile(/[\w\$_]/);return"meta"}}});e("text/x-scala",{name:"clike",keywords:c("abstract case catch class def do else extends final finally for forSome if implicit import lazy match new null object override package private protected return sealed super this throw trait try type val var while with yield _ : = => <- <: <% >: # @ assert assume require print println printf readLine readBoolean readByte readShort readChar readInt readLong readFloat readDouble :: #:: "),types:c("AnyVal App Application Array BufferedIterator BigDecimal BigInt Char Console Either Enumeration Equiv Error Exception Fractional Function IndexedSeq Integral Iterable Iterator List Map Numeric Nil NotNull Option Ordered Ordering PartialFunction PartialOrdering Product Proxy Range Responder Seq Serializable Set Specializable Stream StringBuilder StringContext Symbol Throwable Traversable TraversableOnce Tuple Unit Vector Boolean Byte Character CharSequence Class ClassLoader Cloneable Comparable Compiler Double Exception Float Integer Long Math Number Object Package Pair Process Runtime Runnable SecurityManager Short StackTraceElement StrictMath String StringBuffer System Thread ThreadGroup ThreadLocal Throwable Triple Void"),
multiLineStrings:!0,blockKeywords:c("catch class do else finally for forSome if match switch try while"),defKeywords:c("class def object package trait type val var"),atoms:c("true false null"),indentStatements:!1,indentSwitch:!1,hooks:{"@":function(a){a.eatWhile(/[\w\$_]/);return"meta"},'"':function(a,b){if(!a.match('""'))return!1;b.tokenize=x;return b.tokenize(a,b)},"'":function(a){a.eatWhile(/[\w\$_\xa1-\uffff]/);return"atom"}},modeProps:{closeBrackets:{triples:'"'}}});e("text/x-kotlin",{name:"clike",
keywords:c("package as typealias class interface this super val var fun for is in This throw return break continue object if else while do try when !in !is as?file import where by get set abstract enum open inner override private public internal protected catch finally out final vararg reified dynamic companion constructor init sealed field property receiver param sparam lateinit data inline noinline tailrec external annotation crossinline"),types:c("Boolean Byte Character CharSequence Class ClassLoader Cloneable Comparable Compiler Double Exception Float Integer Long Math Number Object Package Pair Process Runtime Runnable SecurityManager Short StackTraceElement StrictMath String StringBuffer System Thread ThreadGroup ThreadLocal Throwable Triple Void"),
multiLineStrings:!0,blockKeywords:c("catch class do else finally for if where try while enum"),defKeywords:c("class val var object package interface fun"),atoms:c("true false null this"),modeProps:{closeBrackets:{triples:'"'}}});e(["x-shader/x-vertex","x-shader/x-fragment"],{name:"clike",keywords:c("sampler1D sampler2D sampler3D samplerCube sampler1DShadow sampler2DShadow const attribute uniform varying break continue discard return for while do if else struct in out inout"),types:c("float int bool void vec2 vec3 vec4 ivec2 ivec3 ivec4 bvec2 bvec3 bvec4 mat2 mat3 mat4"),
blockKeywords:c("for while do if else struct"),builtin:c("radians degrees sin cos tan asin acos atan pow exp log exp2 sqrt inversesqrt abs sign floor ceil fract mod min max clamp mix step smoothstep length distance dot cross normalize ftransform faceforward reflect refract matrixCompMult lessThan lessThanEqual greaterThan greaterThanEqual equal notEqual any all not texture1D texture1DProj texture1DLod texture1DProjLod texture2D texture2DProj texture2DLod texture2DProjLod texture3D texture3DProj texture3DLod texture3DProjLod textureCube textureCubeLod shadow1D shadow2D shadow1DProj shadow2DProj shadow1DLod shadow2DLod shadow1DProjLod shadow2DProjLod dFdx dFdy fwidth noise1 noise2 noise3 noise4"),
atoms:c("true false gl_FragColor gl_SecondaryColor gl_Normal gl_Vertex gl_MultiTexCoord0 gl_MultiTexCoord1 gl_MultiTexCoord2 gl_MultiTexCoord3 gl_MultiTexCoord4 gl_MultiTexCoord5 gl_MultiTexCoord6 gl_MultiTexCoord7 gl_FogCoord gl_PointCoord gl_Position gl_PointSize gl_ClipVertex gl_FrontColor gl_BackColor gl_FrontSecondaryColor gl_BackSecondaryColor gl_TexCoord gl_FogFragCoord gl_FragCoord gl_FrontFacing gl_FragData gl_FragDepth gl_ModelViewMatrix gl_ProjectionMatrix gl_ModelViewProjectionMatrix gl_TextureMatrix gl_NormalMatrix gl_ModelViewMatrixInverse gl_ProjectionMatrixInverse gl_ModelViewProjectionMatrixInverse gl_TexureMatrixTranspose gl_ModelViewMatrixInverseTranspose gl_ProjectionMatrixInverseTranspose gl_ModelViewProjectionMatrixInverseTranspose gl_TextureMatrixInverseTranspose gl_NormalScale gl_DepthRange gl_ClipPlane gl_Point gl_FrontMaterial gl_BackMaterial gl_LightSource gl_LightModel gl_FrontLightModelProduct gl_BackLightModelProduct gl_TextureColor gl_EyePlaneS gl_EyePlaneT gl_EyePlaneR gl_EyePlaneQ gl_FogParameters gl_MaxLights gl_MaxClipPlanes gl_MaxTextureUnits gl_MaxTextureCoords gl_MaxVertexAttribs gl_MaxVertexUniformComponents gl_MaxVaryingFloats gl_MaxVertexTextureImageUnits gl_MaxTextureImageUnits gl_MaxFragmentUniformComponents gl_MaxCombineTextureImageUnits gl_MaxDrawBuffers"),
indentSwitch:!1,hooks:{"#":l},modeProps:{fold:["brace","include"]}});e("text/x-nesc",{name:"clike",keywords:c("auto if break case register continue return default do sizeof static else struct switch extern typedef float union for goto while enum const volatileas atomic async call command component components configuration event generic implementation includes interface module new norace nx_struct nx_union post provides signal task uses abstract extends"),types:c("int long char short double float unsigned signed void size_t ptrdiff_t"),
blockKeywords:c("case do else for if switch while struct"),atoms:c("null true false"),hooks:{"#":l},modeProps:{fold:["brace","include"]}});e("text/x-objectivec",{name:"clike",keywords:c("auto if break case register continue return default do sizeof static else struct switch extern typedef float union for goto while enum const volatileinline restrict _Bool _Complex _Imaginery BOOL Class bycopy byref id IMP in inout nil oneway out Protocol SEL self super atomic nonatomic retain copy readwrite readonly"),
types:c("int long char short double float unsigned signed void size_t ptrdiff_t"),atoms:c("YES NO NULL NILL ON OFF true false"),hooks:{"@":function(a){a.eatWhile(/[\w\$]/);return"keyword"},"#":l,indent:function(a,b,c){if("statement"==b.type&&/^@\w/.test(c))return b.indented}},modeProps:{fold:"brace"}});e("text/x-squirrel",{name:"clike",keywords:c("base break clone continue const default delete enum extends function in class foreach local resume return this throw typeof yield constructor instanceof static"),
types:c("int long char short double float unsigned signed void size_t ptrdiff_t"),blockKeywords:c("case catch class else for foreach if switch try while"),defKeywords:c("function local class"),typeFirstDefinitions:!0,atoms:c("true false null"),hooks:{"#":l},modeProps:{fold:["brace","include"]}});var n=null;e("text/x-ceylon",{name:"clike",keywords:c("abstracts alias assembly assert assign break case catch class continue dynamic else exists extends finally for function given if import in interface is let module new nonempty object of out outer package return satisfies super switch then this throw try value void while"),
types:function(a){a=a.charAt(0);return a===a.toUpperCase()&&a!==a.toLowerCase()},blockKeywords:c("case catch class dynamic else finally for function if interface module new object switch try while"),defKeywords:c("class dynamic function interface module object package value"),builtin:c("abstract actual aliased annotation by default deprecated doc final formal late license native optional sealed see serializable shared suppressWarnings tagged throws variable"),isPunctuationChar:/[\[\]{}\(\),;\:\.`]/,
isOperatorChar:/[+\-*&%=<>!?|^~:\/]/,isNumberChar:/[\d#$]/,multiLineStrings:!0,typeFirstDefinitions:!0,atoms:c("true false null larger smaller equal empty finished"),indentSwitch:!1,styleDefs:!1,hooks:{"@":function(a){a.eatWhile(/[\w\$_]/);return"meta"},'"':function(a,b){b.tokenize=w(a.match('""')?"triple":"single");return b.tokenize(a,b)},"`":function(a,b){if(!n||!a.match("`"))return!1;b.tokenize=n;n=null;return b.tokenize(a,b)},"'":function(a){a.eatWhile(/[\w\$_\xa1-\uffff]/);return"atom"},token:function(a,
b,c){if(("variable"==c||"variable-3"==c)&&"."==b.prevToken)return"variable-2"}},modeProps:{fold:["brace","import"],closeBrackets:{triples:'"'}}})});
