/*

Copyright (C) 2015 by Marijn Haverbeke <marijnh@gmail.com> and others

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
(function(k){"object"==typeof exports&&"object"==typeof module?k(require("../../lib/codemirror"),require("../xml/xml"),require("../meta")):"function"==typeof define&&define.amd?define(["../../lib/codemirror","../xml/xml","../meta"],k):k(CodeMirror)})(function(k){k.defineMode("markdown",function(w,e){function r(b,a,c){a.f=a.inline=c;return c(b,a)}function s(b){return!b||!/\S/.test(b.string)}function x(b){b.linkTitle=!1;b.em=!1;b.strong=!1;b.strikethrough=!1;b.quote=0;b.indentedCode=!1;t||b.f!=u||(b.f=
m,b.block=n);b.trailingSpace=0;b.trailingSpaceNewLine=!1;b.prevLine=b.thisLine;return b.thisLine=null}function n(b,a){var c=b.sol(),d=!1!==a.list,h=a.indentedCode;a.indentedCode=!1;d&&(0<=a.indentationDiff?(4>a.indentationDiff&&(a.indentation-=a.indentationDiff),a.list=null):0<a.indentation?(a.list=null,a.listDepth=Math.floor(a.indentation/4)):(a.list=!1,a.listDepth=0));var l=null;if(4<=a.indentationDiff)return b.skipToEnd(),h||s(a.prevLine)?(a.indentation-=4,a.indentedCode=!0,g.code):null;if(b.eatSpace())return null;
if((l=b.match(F))&&6>=l[1].length)return a.header=l[1].length,e.highlightFormatting&&(a.formatting="header"),a.f=a.inline,f(a);if(s(a.prevLine)||a.quote||d||h||!(l=b.match(G))){if(b.eat(">"))return a.quote=c?1:a.quote+1,e.highlightFormatting&&(a.formatting="quote"),b.eatSpace(),f(a);if("["===b.peek())return r(b,a,H);if(b.match(I,!0))return a.hr=!0,g.hr;if((s(a.prevLine)||d)&&(b.match(y,!1)||b.match(z,!1)))return c=null,b.match(y,!0)?c="ul":(b.match(z,!0),c="ol"),a.indentation=b.column()+b.current().length,
a.list=!0,a.listDepth++,e.taskLists&&b.match(A,!1)&&(a.taskList=!0),a.f=a.inline,e.highlightFormatting&&(a.formatting=["list","list-"+c]),f(a);if(e.fencedCodeBlocks&&(l=b.match(J,!0)))return a.fencedChars=l[1],c=l[2],k.findModeByName&&(d=k.findModeByName(c))&&(c=d.mime||d.mimes[0]),c=k.getMode(w,c),a.localMode="null"==c.name?null:c,a.localMode&&(a.localState=a.localMode.startState()),a.f=a.block=K,e.highlightFormatting&&(a.formatting="code-block"),a.code=!0,f(a)}else return a.header="="==l[0].charAt(0)?
1:2,e.highlightFormatting&&(a.formatting="header"),a.f=a.inline,f(a);return r(b,a,a.inline)}function u(b,a){var c=q.token(b,a.htmlState);if(t&&null===a.htmlState.tagStart&&!a.htmlState.context&&a.htmlState.tokenize.isInText||a.md_inside&&-1<b.current().indexOf(">"))a.f=m,a.block=n,a.htmlState=null;return c}function K(b,a){if(b.sol()&&a.fencedChars&&b.match(a.fencedChars,!1))return a.localMode=a.localState=null,a.f=a.block=L,null;if(a.localMode)return a.localMode.token(b,a.localState);b.skipToEnd();
return g.code}function L(b,a){b.match(a.fencedChars);a.block=n;a.f=m;a.fencedChars=null;e.highlightFormatting&&(a.formatting="code-block");a.code=!0;var c=f(a);a.code=!1;return c}function f(b){var a=[];if(b.formatting){a.push(g.formatting);"string"===typeof b.formatting&&(b.formatting=[b.formatting]);for(var c=0;c<b.formatting.length;c++)a.push(g.formatting+"-"+b.formatting[c]),"header"===b.formatting[c]&&a.push(g.formatting+"-"+b.formatting[c]+"-"+b.header),"quote"===b.formatting[c]&&(!e.maxBlockquoteDepth||
e.maxBlockquoteDepth>=b.quote?a.push(g.formatting+"-"+b.formatting[c]+"-"+b.quote):a.push("error"))}if(b.taskOpen)return a.push("meta"),a.length?a.join(" "):null;if(b.taskClosed)return a.push("property"),a.length?a.join(" "):null;b.linkHref?a.push(g.linkHref,"url"):(b.strong&&a.push(g.strong),b.em&&a.push(g.em),b.strikethrough&&a.push(g.strikethrough),b.linkText&&a.push(g.linkText),b.code&&a.push(g.code));b.header&&a.push(g.header,g.header+"-"+b.header);b.quote&&(a.push(g.quote),!e.maxBlockquoteDepth||
e.maxBlockquoteDepth>=b.quote?a.push(g.quote+"-"+b.quote):a.push(g.quote+"-"+e.maxBlockquoteDepth));!1!==b.list&&((c=(b.listDepth-1)%3)?1===c?a.push(g.list2):a.push(g.list3):a.push(g.list1));b.trailingSpaceNewLine?a.push("trailing-space-new-line"):b.trailingSpace&&a.push("trailing-space-"+(b.trailingSpace%2?"a":"b"));return a.length?a.join(" "):null}function M(b,a){if(b.match(N,!0))return f(a)}function m(b,a){var c=a.text(b,a);if("undefined"!==typeof c)return c;if(a.list)return a.list=null,f(a);if(a.taskList)return"x"!==
b.match(A,!0)[1]?a.taskOpen=!0:a.taskClosed=!0,e.highlightFormatting&&(a.formatting="task"),a.taskList=!1,f(a);a.taskOpen=!1;a.taskClosed=!1;if(a.header&&b.match(/^#+$/,!0))return e.highlightFormatting&&(a.formatting="header"),f(a);var c=b.sol(),d=b.next();if("\\"===d&&(b.next(),e.highlightFormatting))return c=f(a),d=g.formatting+"-escape",c?c+" "+d:d;if(a.linkTitle){a.linkTitle=!1;var h=d;"("===d&&(h=")");h=(h+"").replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1");if(b.match(new RegExp("^\\s*(?:[^"+h+"\\\\]+|\\\\\\\\|\\\\.)"+
h),!0))return g.linkHref}if("`"===d){c=a.formatting;e.highlightFormatting&&(a.formatting="code");d=f(a);h=b.pos;b.eatWhile("`");h=1+b.pos-h;if(a.code){if(h===B)return a.code=!1,d;a.formatting=c}else B=h,a.code=!0;return f(a)}if(a.code)return f(a);if("!"===d&&b.match(/\[[^\]]*\] ?(?:\(|\[)/,!1))return b.match(/\[[^\]]*\]/),a.inline=a.f=C,g.image;if("["===d&&b.match(/.*\](\(.*\)| ?\[.*\])/,!1))return a.linkText=!0,e.highlightFormatting&&(a.formatting="link"),f(a);if("]"===d&&a.linkText&&b.match(/\(.*\)| ?\[.*\]/,
!1))return e.highlightFormatting&&(a.formatting="link"),c=f(a),a.linkText=!1,a.inline=a.f=C,c;if("<"===d&&b.match(/^(https?|ftps?):\/\/(?:[^\\>]|\\.)+>/,!1))return a.f=a.inline=D,e.highlightFormatting&&(a.formatting="link"),c=f(a),(c?c+" ":"")+g.linkInline;if("<"===d&&b.match(/^[^> \\]+@(?:[^\\>]|\\.)+>/,!1))return a.f=a.inline=D,e.highlightFormatting&&(a.formatting="link"),c=(c=f(a))?c+" ":"",c+g.linkEmail;if("<"===d&&b.match(/^(!--|\w)/,!1))return c=b.string.indexOf(">",b.pos),-1!=c&&(c=b.string.substring(b.start,
c),/markdown\s*=\s*('|"){0,1}1('|"){0,1}/.test(c)&&(a.md_inside=!0)),b.backUp(1),a.htmlState=k.startState(q),c=u,a.f=a.block=c,c(b,a);if("<"===d&&b.match(/^\/\w*?>/))return a.md_inside=!1,"tag";h=!1;if(!e.underscoresBreakWords&&"_"===d&&"_"!==b.peek()&&b.match(/(\w)/,!1)){var l=b.pos-2;0<=l&&(l=b.string.charAt(l),"_"!==l&&l.match(/(\w)/,!1)&&(h=!0))}if("*"===d||"_"===d&&!h){if(!c||" "!==b.peek()){if(a.strong===d&&b.eat(d))return e.highlightFormatting&&(a.formatting="strong"),d=f(a),a.strong=!1,d;
if(!a.strong&&b.eat(d))return a.strong=d,e.highlightFormatting&&(a.formatting="strong"),f(a);if(a.em===d)return e.highlightFormatting&&(a.formatting="em"),d=f(a),a.em=!1,d;if(!a.em)return a.em=d,e.highlightFormatting&&(a.formatting="em"),f(a)}}else if(" "===d&&(b.eat("*")||b.eat("_"))){if(" "===b.peek())return f(a);b.backUp(1)}if(e.strikethrough)if("~"===d&&b.eatWhile(d)){if(a.strikethrough)return e.highlightFormatting&&(a.formatting="strikethrough"),d=f(a),a.strikethrough=!1,d;if(b.match(/^[^\s]/,
!1))return a.strikethrough=!0,e.highlightFormatting&&(a.formatting="strikethrough"),f(a)}else if(" "===d&&b.match(/^~~/,!0)){if(" "===b.peek())return f(a);b.backUp(2)}" "===d&&(b.match(/ +$/,!1)?a.trailingSpace++:a.trailingSpace&&(a.trailingSpaceNewLine=!0));return f(a)}function D(b,a){if(">"===b.next()){a.f=a.inline=m;e.highlightFormatting&&(a.formatting="link");var c=f(a);return(c?c+" ":"")+g.linkInline}b.match(/^[^>]+/,!0);return g.linkInline}function C(b,a){if(b.eatSpace())return null;var c=b.next();
return"("===c||"["===c?(a.f=a.inline=O("("===c?")":"]"),e.highlightFormatting&&(a.formatting="link-string"),a.linkHref=!0,f(a)):"error"}function O(b){return function(a,c){if(a.next()===b){c.f=c.inline=m;e.highlightFormatting&&(c.formatting="link-string");var d=f(c);c.linkHref=!1;return d}a.match(P(b),!0)&&a.backUp(1);c.linkHref=!0;return f(c)}}function H(b,a){return b.match(/^[^\]]*\]:/,!1)?(a.f=Q,b.next(),e.highlightFormatting&&(a.formatting="link"),a.linkText=!0,f(a)):r(b,a,m)}function Q(b,a){if(b.match(/^\]:/,
!0)){a.f=a.inline=R;e.highlightFormatting&&(a.formatting="link");var c=f(a);a.linkText=!1;return c}b.match(/^[^\]]+/,!0);return g.linkText}function R(b,a){if(b.eatSpace())return null;b.match(/^[^\s]+/,!0);void 0===b.peek()?a.linkTitle=!0:b.match(/^(?:\s+(?:"(?:[^"\\]|\\\\|\\.)+"|'(?:[^'\\]|\\\\|\\.)+'|\((?:[^)\\]|\\\\|\\.)+\)))?/,!0);a.f=a.inline=m;return g.linkHref+" url"}function P(b){v[b]||(b=(b+"").replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1"),v[b]=new RegExp("^(?:[^\\\\]|\\\\.)*?("+b+")"));return v[b]}
var t=k.modes.hasOwnProperty("xml"),q=k.getMode(w,t?{name:"xml",htmlMode:!0}:"text/plain");void 0===e.highlightFormatting&&(e.highlightFormatting=!1);void 0===e.maxBlockquoteDepth&&(e.maxBlockquoteDepth=0);void 0===e.underscoresBreakWords&&(e.underscoresBreakWords=!0);void 0===e.taskLists&&(e.taskLists=!1);void 0===e.strikethrough&&(e.strikethrough=!1);void 0===e.tokenTypeOverrides&&(e.tokenTypeOverrides={});var B=0,g={header:"header",code:"comment",quote:"quote",list1:"variable-2",list2:"variable-3",
list3:"keyword",hr:"hr",image:"tag",formatting:"formatting",linkInline:"link",linkEmail:"link",linkText:"link",linkHref:"string",em:"em",strong:"strong",strikethrough:"strikethrough"},p;for(p in g)g.hasOwnProperty(p)&&e.tokenTypeOverrides[p]&&(g[p]=e.tokenTypeOverrides[p]);var I=/^([*\-_])(?:\s*\1){2,}\s*$/,y=/^[*\-+]\s+/,z=/^[0-9]+([.)])\s+/,A=/^\[(x| )\](?=\s)/,F=e.allowAtxHeaderWithoutSpace?/^(#+)/:/^(#+)(?: |$)/,G=/^ *(?:\={1,}|-{1,})\s*$/,N=/^[^#!\[\]*_\\<>` "'(~]+/,J=new RegExp("^("+(!0===e.fencedCodeBlocks?
"~~~+|```+":e.fencedCodeBlocks)+")[ \\t]*([\\w+#]*)"),v=[],E={startState:function(){return{f:n,prevLine:null,thisLine:null,block:n,htmlState:null,indentation:0,inline:m,text:M,formatting:!1,linkText:!1,linkHref:!1,linkTitle:!1,em:!1,strong:!1,header:0,hr:!1,taskList:!1,list:!1,listDepth:0,quote:0,trailingSpace:0,trailingSpaceNewLine:!1,strikethrough:!1,fencedChars:null}},copyState:function(b){return{f:b.f,prevLine:b.prevLine,thisLine:b["this"],block:b.block,htmlState:b.htmlState&&k.copyState(q,b.htmlState),
indentation:b.indentation,localMode:b.localMode,localState:b.localMode?k.copyState(b.localMode,b.localState):null,inline:b.inline,text:b.text,formatting:!1,linkTitle:b.linkTitle,code:b.code,em:b.em,strong:b.strong,strikethrough:b.strikethrough,header:b.header,hr:b.hr,taskList:b.taskList,list:b.list,listDepth:b.listDepth,quote:b.quote,indentedCode:b.indentedCode,trailingSpace:b.trailingSpace,trailingSpaceNewLine:b.trailingSpaceNewLine,md_inside:b.md_inside,fencedChars:b.fencedChars}},token:function(b,
a){a.formatting=!1;if(b!=a.thisLine){var c=a.header||a.hr;a.header=0;a.hr=!1;if(b.match(/^\s*$/,!0)||c){x(a);if(!c)return null;a.prevLine=null}a.prevLine=a.thisLine;a.thisLine=b;a.taskList=!1;a.trailingSpace=0;a.trailingSpaceNewLine=!1;a.f=a.block;var c=b.match(/^\s*/,!0)[0].replace(/\t/g,"    ").length,d=4*Math.floor((c-a.indentation)/4);4<d&&(d=4);d=a.indentation+d;a.indentationDiff=d-a.indentation;a.indentation=d;if(0<c)return null}return a.f(b,a)},innerMode:function(b){return b.block==u?{state:b.htmlState,
mode:q}:b.localState?{state:b.localState,mode:b.localMode}:{state:b,mode:E}},blankLine:x,getType:f,fold:"markdown"};return E},"xml");k.defineMIME("text/x-markdown","markdown")});
